qa/urls.py
from django.conf.urls import url
from . import views

app_name = 'qa'

urlpatterns = [
    url(r'^$', views.question_list, name='home'),
    url(r'^answers/$', views.add_answer, name='add_answer'),
    url(r'^question/(?P<pk>\d+)/$', views.question_detail,
        name='question_detail'),
    url(r'^search/$', views.search,
        name='search'),
    url(r'^comment/(?P<pk>\d+)/$', views.handle_comments,
        name='comment')
]

quora/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('qa/', include('qa.urls'))
]

qa/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True, blank=False)

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answer")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    answer_content = models.TextField()


class Comments(models.Model):
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=200)

qa/forms.py
from django import forms
from django.forms import ModelForm

# from markdownx.fields import MarkdownxFormField

from .models import Question, Answer, Comments
from crispy_forms.helper import FormHelper


class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ('title',)


class AnswerForm(ModelForm):

    answer_content = forms.CharField(max_length=200, widget=forms.Textarea,
                                     label='')
    question_id = forms.CharField(max_length=200, widget=forms.HiddenInput())

    class Meta:
        model = Answer
        fields = ('answer_content', 'question_id')


class CommentForm(ModelForm):
    comment_content = forms.CharField(max_length=200,
                                      label='', widget=forms.TextInput(
                                        attrs={
                                            'placeholder': 'comment here...'}))

    class Meta:
        model = Comments
        fields = ('comment_content',)

qa/views.py
from django.shortcuts import render
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# from django.http import HttpRequest

# Create your views here.


def question_list(request):
    template_name = 'qa/home.html'
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect("qa:home")
        else:
            messages.error(request, 'Question already exists or invalid input')
            return redirect('qa:home')
    else:
        question_form = QuestionForm(request.POST)
        questions = Question.objects.prefetch_related('answer')
        return render(
            request, template_name, {'questions': questions,
                                     'form': question_form,
                                     })


@login_required
def add_answer(request):
    template_name = 'qa/answers.html'
    if request.method == 'POST':
        question_id = request.POST.get('question_id')
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            answer = answer_form.save(commit=False)
            answer.user = request.user
            answer.question = Question.objects.get(id=question_id)
            answer.save()
        return redirect("qa:add_answer")
    else:
        question_form = QuestionForm()
        answer_form = AnswerForm()
        questions = Question.objects.all()
        for question in questions:
            question.first_answer = question.answer.first()
        return render(
            request, template_name, {'questions': questions,
                                     'form': question_form,
                                     'answer': answer_form
                                     })


@login_required
def question_detail(request, pk):
    template_name = 'qa/question_detail.html'
    if request.method == 'POST':
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            answer = answer_form.save(commit=False)
            answer.user = request.user
            answer.question = Question.objects.get(id=pk)
            answer.save()
            return redirect('qa:question_detail', pk=pk)
        else:
            messages.error(request, 'Invalid input')
            return redirect('qa:question_detail', pk=pk)
    else:
        answer_form = AnswerForm()
        question = Question.objects.get(id=pk)
        answers = Answer.objects.filter(question=question)
        question.no_of_answers = Answer.objects.filter(
            question=question).count()

        for answer in answers:
            answer.list_of_comments = answer.comments.all()
        comment_form = CommentForm()
        return render(request, template_name, {'selected_question': question,
                                               'answer_form': answer_form,
                                               'answers': answers,
                                               'comment_form': comment_form,
                                               })


@login_required
def handle_comments(request, pk):
    if request.method == 'POST':
        # id = request.POST.get('answer_id')
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.answer = Answer.objects.get(id=pk)
            comment.save()
            qid = comment.answer.question.id
            return redirect("qa:question_detail", pk=qid)


@login_required
def search(request):
    status = {}
    if request.method == 'POST':
        search_data = request.POST.get('search')
        status = Question.objects.filter(title__icontains=search_data)

        for question in status:
            question.no_of_answers = len(question.answer.all())
            question.first_answer = question.answer.first()
    return render(request, "qa/search.html", {"status": status})

templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <script src='main.js'></script>
</head>

<body>
    <nav>
        <div class="menu">
            <img src="{% static 'images/quora.jpg'%}" width="100px" height="70px">
            <a href="{% url 'qa:home' %}"><i class="fas fa-home"></i>Home</a>
            <a href="{% url 'qa:add_answer' %}"><i class="fas fa-edit"></i>Answer</a>
            <div class="search-container">
                <i class="fas fa-search search"> </i>
                <form method="POST" action="{% url 'qa:search' %}">
                    {% csrf_token %}
                    <input class="form-control form-control-sm" type="text" name="search" placeholder="Search quora">
                    <input type="submit" style="position: absolute; left: -9999px" />
                </form>
            </div>
            <img class="user" src="{% static 'images/user.png'%}">
            {% if request.user.username %}
            <span>{{request.user.username}}</span>
            {% else %}
            <span><a href="http://localhost:8000/admin/">login</a></span>
            {%endif %}
            <a class="btn btn-danger" style="color:white" data-toggle="modal" data-target="#myModal" role="button">Add
                Question</a>
        </div>
    </nav>

    <!-- Modal -->
    {% block modal %}
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <p>You're not logged in.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    
</body>

</html>

templates/qa/answers.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% block modal %}
{% load static %}
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Enter your Question</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary" type="submit">Submit</button>

                </form>

            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>

        </div>

    </div>
</div>
{% endblock %}
<div class="question-list">
        {% for message in messages %}

        <div class="alert">
          {{ message }}
  
        </div>
        {% endfor %}
    <div class="add-question">
        <div> <span> <img class="user" src="{% static 'images/user.png'%}">
                {{request.user}}</span></div><br>
        <a data-toggle="modal" data-target="#myModal"><strong>What is your question link?</strong></a>


    </div>

    {% for question in questions %}


    <div class="each-question">
        <div class="question-tags">Question added. Technology</div><br>
        <a class="question-link" href="{% url 'qa:question_detail' question.id %}">{{ question.title }}</a><br><br>
        <div class="answer-pen" id="{{ question.id }}"><i class="fas fa-edit"></i>Answer</div>
        <div class="add-answer" id="add-answer{{ question.id }}">
            <div class="answer-header"> <span><i class="fa fa-user"></i>
                    {{request.user}}</span></div>
            <form method="POST">
                {% csrf_token %}

                {{ answer|crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>

            </form>


        </div>
        <script>
            $(document).ready(function () {
                $("#{{ question.id }}").click(function () {
                    $("#add-answer{{ question.id }}").toggle()
                    $("#id_question_id").val("{{ question.id }}")
                })
            })
        </script>


    </div>

    {% endfor %}





    {% endblock %}

</div>

templates/qa/home.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
{% load crispy_forms_tags %}
{% block modal %}
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Enter your Question</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<div class="question-list">
        {% for message in messages %}

        <div class="alert">
          {{ message }}
  
        </div>
        {% endfor %}
  
    <div class="add-question">
        <div> <span><img class="user" src="{% static 'images/user.png'%}">
                {{request.user}}</span></div><br>
        <a data-toggle="modal" data-target="#myModal"><strong>What is your question link?</strong></a>


    </div>
    {% for question in questions %}
    <div class="each-question">
        <div class="question-tags">Question added. Technology</div><br>
        <a class="question-link" href="{% url 'qa:question_detail' question.id %}">{{ question.title }}</a><br><br>

        <div class="answer-count">{{ question.answer.count }} Answers</div><br>
        <div class="username"> <span><img class="user" src="{% static 'images/user.png'%}">

                {{ question.answer.first.user.username }}</span></div><br>
        <div class="answer-content">{{ question.answer.first.answer_content }}</div>


    </div>

    {% endfor %}



    {% endblock %}
</div>

templates/qa/question_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block modal %}
{%load static %}
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Enter your Question</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
{% endblock %}
{% block content %}
<div class="question-detail">
    <div>{{ selected_question }}</div>
    <div class="answer-pen" id="{{ selected_question.id }}"><i class="fas fa-edit"></i>Answer</div>
    <div class="add-answer" id="add-answer{{ selected_question.id }}">
        <div class="answer-header"> <span><img class="user" src="{% static 'images/user.png'%}">
                {{request.user}}</span></div>
        <form method="POST">
            {% csrf_token %}
            {{ answer_form|crispy }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
    <script>
        $(document).ready(function () {
            $("#{{ selected_question.id }}").click(function () {
                $("#add-answer{{ selected_question.id }}").toggle()
                $("#id_question_id").val("{{ selected_question.id }}")

            })
        })
    </script>
    <div class="answers-count">{{ selected_question.no_of_answers }} Answers</div>
    <hr>
</div>

<div class="answers">
    {% for answer in answers %}
    <div class="answer">
        <div class="username"> <span><img class="user" src="{% static 'images/user.png'%}">
                {{answer.user.username}}</span></div><br>
        <div class="answer-content">{{answer.answer_content}}</div><br>
        <div class="comment-container">
            {% for com in answer.list_of_comments %}
            <div class="individual-comment">
                <span> {{ com.user.username }} : {{ com.comment_content }} </span>
            </div>
            {% endfor %}
        </div>
        <div class="comment">
            <form  method="POST" action="{% url 'qa:comment' answer.pk %}">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <button class="btn btn-default" type="submit">comment</button>
                <div id="dummy-identifier"></div>
            </form>
            
        </div>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/qa/search.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
{% load crispy_forms_tags %}
{% block modal %}
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Enter your Question</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary" type="submit">Submit</button>

                </form>

            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>

        </div>

    </div>
</div>
{% endblock %}
<div class="question-list">
    <div class="add-question">
        <div> <span><img class="user" src="{% static 'images/user.png'%}">
                {{request.user}}</span></div><br>
        <a data-toggle="modal" data-target="#myModal"><strong>What is your question link?</strong></a>


    </div>
    {% for question in status %}


    <div class="each-question">
        <div class="question-tags">Question added. Technology</div><br>
        <a class="question-link" href="{% url 'qa:question_detail' question.id %}">{{ question.title }}</a><br><br>

        <div class="answer-count">{{ question.no_of_answers }} Answers</div><br>

        <div class="username"> <span><img class="user" src="{% static 'images/user.png'%}">
                {{ question.first_answer.user.username }}</span></div><br>
        <div class="answer-content">{{ question.first_answer.answer_content }}</div>


    </div>

    {% endfor %}



    {% endblock %}
</div>